name = "insighthunter-api"
main = "src/index.ts"
compatibility_date = "2025-08-16"

[[d1_databases]]
binding = "env.DB"
database_name = "env.DB"
database_id = "insighthunter_db"

{
  "ai": {
    "binding": "AI"
  }
}
